FROM mcr.microsoft.com/playwright:v1.50.1-jammy

WORKDIR /app

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

COPY package*.json ./
RUN npm install

COPY . .

# Generate Prisma client
RUN npx prisma generate

# Final check if dependencies are installed correctly for browsers
RUN npx playwright install --with-deps chromium

CMD ["npm", "test"]
